import type { Command } from "commander";

/**
 * The command line as data, declared once and read by everything that depends on it.
 *
 * `docs/reference/compatibility.md` calls the CLI's flags and exit codes a public surface, and the
 * SDK's half of that promise is kept by a committed inventory: a name leaving
 * `docs/generated/sdk-api-inventory.json` is a diff somebody has to argue for. The command line had
 * no equivalent. It was fifteen `.option()` calls in `index.ts`, and removing one looked exactly
 * like editing one.
 *
 * So the flags live here, and three readers consume this file rather than each other:
 *
 * - {@link applyCliSurface} builds the Commander program `index.ts` runs;
 * - `scan-options.ts` validates against the same value sets the help text prints;
 * - `scripts/generate-cli-inventory.mjs` builds the same program with no actions attached and
 *   records what Commander made of it.
 *
 * The inventory is generated by giving these strings to Commander and reading the `Option` objects
 * back, rather than by matching `-f, --format <format>` with a regular expression written here. A
 * flag string means whatever the library parsing it decides, and a second parser would eventually
 * disagree with the first about a corner of the syntax nobody tested.
 *
 * What is **not** here: help formatting, the order options happen to appear in a paragraph, and the
 * action bodies. The inventory records none of those, on purpose — a contract that pinned the
 * wording of a description would fail on a typo fix and say "breaking change".
 */

/** Formats `scan` renders. The command's help text and its validator read this one list. */
export const SCAN_FORMATS = ["json", "markdown", "sarif", "html"] as const;

/**
 * Formats a journey renders.
 *
 * Two, not four: SARIF and HTML are refused with a reason rather than unimplemented, and those
 * reasons live beside the refusal in `index.ts` because they are arguments rather than data.
 */
export const JOURNEY_FORMATS = ["json", "markdown"] as const;

/** Formats `rules` and `explain` render. */
export const RULE_LISTING_FORMATS = ["text", "json"] as const;

/** Severities `--fail-on` accepts, most severe first, as the help text lists them. */
export const FAIL_ON_SEVERITIES = ["high", "medium", "low", "info"] as const;

/** Input kinds `rules --runtime` accepts, matching the engine's `Runtime`. */
export const RUNTIMES = ["html", "dom", "ast", "figma"] as const;

/** The program a `bin` entry installs, and the name every refusal is prefixed with. */
export const PROGRAM_NAME = "fairux";

export const PROGRAM_DESCRIPTION =
  "Detect UI patterns that may distort user decision-making (UX risk signals).";

/**
 * What each exit code means, which is a contract a script depends on more tightly than a flag.
 *
 * Changing one of these meanings breaks every pipeline that branches on it while looking like no
 * change at all — nothing in the help text mentions an exit code, so the only way a consumer learns
 * it moved is a build that stops failing. Recorded here so a change to one is a change to a
 * committed artifact.
 */
export const EXIT_CODES: readonly { readonly code: number; readonly meaning: string }[] =
  Object.freeze([
    Object.freeze({
      code: 0,
      meaning:
        "the command did what it was asked, and nothing it was told to fail on was found. A scan " +
        "that reports findings still exits 0 unless --fail-on names a severity they meet",
    }),
    Object.freeze({
      code: 1,
      meaning:
        "the run failed, or a finding met --fail-on. Also a --fix-write that was asked for and did " +
        "not land, and a target that matched no scannable file",
    }),
    Object.freeze({
      code: 2,
      meaning:
        "the invocation is wrong and nothing happened: an unknown value, two flags that contradict " +
        "each other, a flag this run would accept and ignore, an unknown rule id, or a journey " +
        "file that is not there. No discovery, no scan, no RulePack import, no output file",
    }),
  ]);

/**
 * What a description needs that this file cannot know.
 *
 * One option's help text lists the Risk Index models, and those come from `@fairux/rules` rather
 * than from the command line — a model arriving is a rule-set change, not a CLI change. Passing it
 * in keeps this module free of the engine, which is what lets the inventory generator load it
 * without building anything.
 */
export interface CliHelpContext {
  readonly riskIndexModelVersions: readonly string[];
  readonly defaultRiskIndexModel: string;
}

export interface CliOptionSpec {
  /** Exactly what Commander is given, and the only place the flag's spelling is written. */
  readonly flags: string;
  readonly description: string | ((context: CliHelpContext) => string);
  /** Supplied to Commander, and recorded in the inventory: changing one changes what a run does. */
  readonly defaultValue?: string | boolean;
  /** The values this option accepts, when the CLI is the thing that decides them. */
  readonly values?: readonly string[];
  /** Repeating the flag collects, rather than replacing. */
  readonly repeatable?: boolean;
}

export interface CliArgumentSpec {
  /** In Commander's own notation, so required and variadic are its answer rather than ours. */
  readonly name: string;
  readonly description: string;
}

export interface CliCommandSpec {
  readonly name: string;
  readonly description?: string;
  readonly argument?: CliArgumentSpec;
  readonly options: readonly CliOptionSpec[];
}

/** `a | b | c`, the form every format description in this CLI already uses. */
function pipeList(values: readonly string[]): string {
  return values.join(" | ");
}

/**
 * The three options every command takes, written once.
 *
 * They were four copies of the same two sentences, and the copies had already drifted: `scan`
 * refused `--config` beside `--ignore-config` and the other three took the explicit config and ran.
 * That is fixed in `scan-options.ts`; this is the half of it that keeps the *descriptions* from
 * drifting apart again.
 */
const CONFIG_OPTION: CliOptionSpec = {
  flags: "--config <path>",
  description:
    "path to a fairux.config file (.json, or executable .ts/.mjs/.js/.cjs you trust); " +
    "when omitted, only fairux.config.json is auto-discovered",
};

const IGNORE_CONFIG_OPTION: CliOptionSpec = {
  flags: "--ignore-config",
  description: "skip automatic config discovery",
  defaultValue: false,
};

const RULE_PACK_OPTION: CliOptionSpec = {
  flags: "--rule-pack <path>",
  description: "load an external RulePack (repeatable). It is executable code and is not sandboxed",
  repeatable: true,
};

/** The commands, in the order `fairux --help` lists them. */
export const CLI_COMMANDS: readonly CliCommandSpec[] = Object.freeze([
  Object.freeze({
    name: "scan",
    argument: {
      name: "<path>",
      description: "path to a file, directory, or glob pattern to scan (use '-' for stdin)",
    },
    options: Object.freeze([
      {
        flags: "-f, --format <format>",
        description: `output format: ${pipeList(SCAN_FORMATS)}`,
        defaultValue: "markdown",
        values: SCAN_FORMATS,
      },
      {
        flags: "--include-experimental",
        description: "also run experimental (heuristic) rules",
      },
      CONFIG_OPTION,
      IGNORE_CONFIG_OPTION,
      {
        flags: "--stdin-filename <name>",
        description:
          "name the document piped to '-' so its extension picks the adapter (default stdin.html)",
      },
      {
        flags: "--no-ignore",
        description: "scan paths a discovered .fairuxignore would exclude",
      },
      {
        flags: "--baseline <file>",
        description:
          "subtract findings recorded in a baseline file — accepted risk, not resolved risk",
      },
      {
        flags: "--write-baseline <file>",
        description: "write this scan's findings to a baseline file instead of reporting them",
      },
      {
        flags: "--suppress <file>",
        description:
          "apply a suppressions file — each entry needs a reason, and may carry an expiry",
      },
      RULE_PACK_OPTION,
      {
        flags: "--fail-on <severity>",
        description:
          "exit with code 1 if any finding meets or exceeds this severity " +
          `(${pipeList(FAIL_ON_SEVERITIES)})`,
        values: FAIL_ON_SEVERITIES,
      },
      {
        flags: "--risk-index <file>",
        description:
          "also write a FairUX Risk Index for this scan to a file. It never changes stdout or the exit code",
      },
      {
        flags: "--risk-index-model <version>",
        // The one description this file cannot write on its own, and the one option whose value set
        // is deliberately absent from the inventory: the models are the rule set's, and a model
        // arriving there is not a change to the command line.
        description: (context: CliHelpContext) =>
          `which model scores it: ${pipeList([...context.riskIndexModelVersions])} ` +
          `(default ${context.defaultRiskIndexModel}). ` +
          "Two scores are comparable only when their versions match",
      },
      {
        flags: "--fix-dry-run",
        description: "report which remediations would apply, and change nothing",
      },
      {
        flags: "--fix-write",
        description:
          "apply safe remediations. Never applies a review-required one, and there is no flag that does",
      },
    ]),
  }),
  Object.freeze({
    name: "scan-journey",
    description: "scan an ordered flow of documents already on disk. Never launches a browser",
    argument: {
      name: "<file>",
      description: "path to a journey file (JSON) naming the documents of an ordered flow",
    },
    options: Object.freeze([
      {
        flags: "-f, --format <format>",
        description: `output format: ${pipeList(JOURNEY_FORMATS)}`,
        defaultValue: "markdown",
        values: JOURNEY_FORMATS,
      },
      {
        flags: "--include-experimental",
        description: "also run experimental (heuristic) rules",
      },
      CONFIG_OPTION,
      IGNORE_CONFIG_OPTION,
      RULE_PACK_OPTION,
      {
        flags: "--fail-on <severity>",
        description:
          "exit with code 1 if any finding — the flow's own or any step's — meets or exceeds this severity",
        values: FAIL_ON_SEVERITIES,
      },
    ]),
  }),
  Object.freeze({
    name: "rules",
    description: "list the rules a scan would run, with their effective state",
    options: Object.freeze([
      {
        flags: "-f, --format <format>",
        description: `output format: ${pipeList(RULE_LISTING_FORMATS)}`,
        defaultValue: "text",
        values: RULE_LISTING_FORMATS,
      },
      {
        flags: "--include-experimental",
        description: "also list experimental (heuristic) rules as enabled",
      },
      CONFIG_OPTION,
      IGNORE_CONFIG_OPTION,
      RULE_PACK_OPTION,
      {
        flags: "--runtime <runtime>",
        description: `mark rules an input of this kind cannot run at all: ${RUNTIMES.join(" | ")}`,
        values: RUNTIMES,
      },
    ]),
  }),
  Object.freeze({
    name: "explain",
    description: "explain one rule: what it needs, what it cannot see, and the sources behind it",
    argument: {
      name: "<rule-id>",
      description: "id of the rule to explain, e.g. consent/checked-checkbox",
    },
    options: Object.freeze([
      {
        flags: "-f, --format <format>",
        description: `output format: ${pipeList(RULE_LISTING_FORMATS)}`,
        defaultValue: "text",
        values: RULE_LISTING_FORMATS,
      },
      {
        flags: "--include-experimental",
        description: "resolve enablement as if experimental rules were enabled",
      },
      CONFIG_OPTION,
      IGNORE_CONFIG_OPTION,
      RULE_PACK_OPTION,
    ]),
  }),
]);

/** Repeating a flag collects its values; the first one starts the list. */
function collect(value: string, previous: string[] = []): string[] {
  return [...previous, value];
}

/**
 * Attach every command and option above to a program, and hand back the commands by name.
 *
 * `index.ts` adds an action to each; the inventory generator adds none and reads the result. One
 * wiring, so the artifact describes the program that ships rather than a second program built to
 * resemble it.
 */
export function applyCliSurface(
  program: Command,
  context: CliHelpContext,
): ReadonlyMap<string, Command> {
  const commands = new Map<string, Command>();
  for (const spec of CLI_COMMANDS) {
    const command = program.command(spec.name);
    if (spec.description) command.description(spec.description);
    if (spec.argument) command.argument(spec.argument.name, spec.argument.description);
    for (const option of spec.options) {
      const description =
        typeof option.description === "function" ? option.description(context) : option.description;
      if (option.repeatable) command.option(option.flags, description, collect);
      else if (option.defaultValue !== undefined)
        command.option(option.flags, description, option.defaultValue);
      else command.option(option.flags, description);
    }
    commands.set(spec.name, command);
  }
  return commands;
}
